var SchoolData = [
{'coordinate': [42.2558, -77.7861], 'collegeName': 'Alfred University', 'students': ['Julia Lauer']},
{'coordinate': [38.93775105, -77.08948226], 'collegeName': 'American University', 'students': ['Anisha Patwardhan', 'PJ Wisowaty', 'Uma Choudhury']},
{'coordinate': [33.424564, -111.928001], 'collegeName': 'Arizona State University', 'students': ['Andrew Vargha']},
{'coordinate': [34.1689, -118.1852], 'collegeName': 'Art Center College of Design', 'students': ['Ibby Day']},
{'coordinate': [42.3857, -71.2217], 'collegeName': 'Bentley University', 'students': ['Maki Yasuda']},
{'coordinate': [42.3857, -71.2217], 'collegeName': 'Berkeley City College', 'students': ['Atusa Assadi']},
{'coordinate': [42.3352916, -71.1703275], 'collegeName': 'Boston College', 'students': ['Katie  Passarello']},
{'coordinate': [42.3462, -71.09], 'collegeName': 'Boston Conservatory', 'students': ['Georgina Wu']},
{'coordinate': [42.35050035, -71.10255976], 'collegeName': 'Boston University', 'students': ['Andy Chang', 'Lindsay Chen', 'Meredith Cummings', 'Cameron Diep', 'Cole Hechtman', 'Nadia Leinhos']},
{'coordinate': [42.36634305, -71.25799473], 'collegeName': 'Brandeis University', 'students': ['Annabelle Hu', 'Deepali Sastry']},
{'coordinate': [40.25142785, -111.6492], 'collegeName': 'Brigham Young University', 'students': ['Isabel Black', 'Belle Doughman', 'Jake Doughman ']},
{'coordinate': [41.8268682, -71.40123136], 'collegeName': 'Brown University', 'students': ['Joelle Dong', 'Max Lenail', 'Alicia Mies', 'Marion Sellier', 'Brian Tracy']},
{'coordinate': [40.02813555, -75.31592044], 'collegeName': 'Bryn Mawr College', 'students': ['Hiya Datta', 'Madhumita Gupta', 'Zoe Sego']},
{'coordinate': [40.9549, -76.8847], 'collegeName': 'Bucknell University', 'students': ['Jared  Stanley ', 'Hollis Caswell', 'Colin Fee', 'Steven Marinkovich', 'Jordan Quigley']},
{'coordinate': [35.3052, -120.6624], 'collegeName': 'Cal Poly San Luis Obispo', 'students': ['Sajjad Ahsan', 'Jovanna Cala Vella', 'Austin Cheok', 'Katie Cox', 'Nina Lerrick', 'Aman Mittal', 'Zachariah  Strassberg-Phillips', 'Andrea Yau-Chan', 'Claire Eberhart', 'Ally  Hutson']},
{'coordinate': [37.8363, -122.2504], 'collegeName': 'California College of the Arts', 'students': ['Joyce Choi']},
{'coordinate': [34.1377, -118.1253], 'collegeName': 'California Institute of Technology', 'students': ['Spencer Morgenfeld', 'Andrew Ho', 'Galilea von Ruden']},
{'coordinate': [34.3933, -118.5668], 'collegeName': 'California Institute of the Arts', 'students': ['Jason Pollak']},
{'coordinate': [33.7838, -118.1141], 'collegeName': 'California State Long Beach', 'students': ['Adrian Smith']},
{'coordinate': [44.4614, -93.1561], 'collegeName': 'Carleton College', 'students': ['Gregor Dairaghi']},
{'coordinate': [40.4419396, -79.94497646], 'collegeName': 'Carnegie Mellon University', 'students': ['Timothy Liu', 'Naveen Pai', 'Shivum Agarwal', 'Yael Ben-Shachar']},
{'coordinate': [41.50769375, -81.60882971], 'collegeName': 'Case Western Reserve University', 'students': ['Bethany Shiang']},
{'coordinate': [44.0714, -121.3486], 'collegeName': 'Central Oregon Community College', 'students': ['Calvin Drez']},
{'coordinate': [33.79351385, -117.8514866], 'collegeName': 'Chapman University', 'students': ['Sandra Bouissou', 'Nathalia Castillo', 'Melissa Cheng', 'Kira Enriquez', 'Frank Entriken', 'Joanna Falla', 'Samantha Guillet', 'Eli Gwin-Kerr', 'Elise Wong', 'Christian Rider', 'Allison  Shih', 'Molly Weitzman']},
{'coordinate': [34.1023497, -117.7067162], 'collegeName': 'Claremont McKenna College', 'students': ['Noah  Galper', 'Jessica Lee', 'Jennifer Zhuge']},
{'coordinate': [37.414, -121.9409], 'collegeName': 'Cogswell Polytechnical College', 'students': ['Jongseo  Park']},
{'coordinate': [40.8069705, -73.96293293], 'collegeName': 'Columbia University', 'students': ['Jackson Kienitz', 'Peter Maroulis', 'Clay Watson', 'Ericka Wu', 'Alice Zhang']},
{'coordinate': [42.4489498, -76.47468305], 'collegeName': 'Cornell University', 'students': ['Kenneth Cheung', 'Andrew Jozefov']},
{'coordinate': [34.1621, -119.0434], 'collegeName': 'CSU Channel Islands', 'students': ['Taylor  Duncan']},
{'coordinate': [39.7292614, -121.8443131], 'collegeName': 'CSU Chico State', 'students': ['Tommy Smale']},
{'coordinate': [40.875781, -124.07856], 'collegeName': 'CSU Humboldt State', 'students': ['Emily  Read', 'Michel-Ange Siaba']},
{'coordinate': [49.2036, -122.9127], 'collegeName': 'Douglas College', 'students': ['Jeanette Andrews']},
{'coordinate': [39.9569644, -75.18995131], 'collegeName': 'Drexel University', 'students': ['Ally Zhu', 'Nicholas McCluskey', 'Siddharth Srinivasan']},
{'coordinate': [36.0973667, -79.50876473], 'collegeName': 'Elon University', 'students': ['Nick Smallwood']},
{'coordinate': [33.79586765, -84.32778951], 'collegeName': 'Emory University', 'students': ['Andrew Yin']},
{'coordinate': [37.3617114, -122.1282716], 'collegeName': 'Foothill', 'students': ['Sukar Ross']},
{'coordinate': [37.3617114, -122.1282716], 'collegeName': 'Foothill College', 'students': ['Aisha Chabane', 'Kayla Christensen', 'Shalana Erlich', 'Arthur Halsted', 'Christopher Angulo', 'Zachary Gibson', 'Mackenzie Glassford', 'Will Leighton', 'Magdalena  Renteria', 'Yusuf Rizk', 'Evan Welsh', 'Santiago Ruiz']},
{'coordinate': [38.8316, -77.3121], 'collegeName': 'George Mason University', 'students': ['Seth Goyal']},
{'coordinate': [38.9044038, -77.04780326], 'collegeName': 'George Washington University', 'students': ['Avery Pearson']},
{'coordinate': [41.7491, -92.7201], 'collegeName': 'Grinnell College', 'students': ['Ryan Chang']},
{'coordinate': [42.36782045, -71.12666173], 'collegeName': 'Harvard University', 'students': ['Gaby Pelayo']},
{'coordinate': [39.3299, -76.6205], 'collegeName': 'Johns Hopkins University', 'students': ['Aidan Maese-Czeropski']},
{'coordinate': [40.6986, -75.2087], 'collegeName': 'Lafayette College', 'students': ['Ethan Stern']},
{'coordinate': [40.6069, -75.3783], 'collegeName': 'Lehigh University', 'students': ['Anna Moragne']},
{'coordinate': [45.4524, -122.6774], 'collegeName': 'Lewis and Clark College', 'students': ['Lydia Miller', 'Max Usman', 'Nicholas  Campen ']},
{'coordinate': [33.9708705, -118.4186976], 'collegeName': 'Loyola Marymount University', 'students': ['Declan Flanders']},
{'coordinate': [39.3076707, -76.6214825], 'collegeName': 'Maryland Institute College of Art', 'students': ['Yoon Jung Cho', 'Kobe Sullivan ']},
{'coordinate': [42.3583961, -71.09567771], 'collegeName': 'Massachusetts Institute of Technology', 'students': ['Maya Lathi', 'Kent Slaney']},
{'coordinate': [37.4561, -122.1921], 'collegeName': 'Menlo College', 'students': ['Sara Aguilar']},
{'coordinate': [40.7292414, -73.9961861], 'collegeName': 'New York University', 'students': ['Skylar Burris', 'Alec Cohen-Schisler', 'Alia Cuadros-Contreras', 'John Dai', 'Joey Kellison-Linn', 'Sam Lee', 'Dylan Polley ', 'Yotam Ponte', 'Alex  Song', 'Daniel Taratorin', 'Elizabeth Wilkinson', 'Lauren Koyama', 'Rianna Steiner']},
{'coordinate': [42.3383668, -71.0879351], 'collegeName': 'Northeastern University', 'students': ['Jasmine Abeyta', 'Alexander Beaudry', 'Griffin Byer', 'Jackson Doerr', 'Kimberly Markevitch', 'Erin Mittmann']},
{'coordinate': [42.0550773, -87.6758117], 'collegeName': 'Northwestern University', 'students': ['Jonathan Chen', 'Peter Snodgrass', 'Kathy Yan', 'Chirag Akella']},
{'coordinate': [37.5178, -122.2853], 'collegeName': 'Notre Dame de Namur University', 'students': ['Ciara Bleahen']},
{'coordinate': [34.1273624, -118.2110362], 'collegeName': 'Occidental College', 'students': ['David Tayeri', 'Alissa  Bernstein']},
{'coordinate': [45.527, -122.6782], 'collegeName': 'Pacific Northwest College of Art', 'students': ['Yasmin Correa']},
{'coordinate': [40.7353, -73.9946], 'collegeName': 'Parsons School of Design', 'students': ['Nancy Zhong']},
{'coordinate': [40.7982, -77.8599], 'collegeName': 'Pennsylvania State University', 'students': ['Wesley Kim', 'Ethan Bundy']},
{'coordinate': [34.1037196, -117.7056738], 'collegeName': 'Pitzer College', 'students': ['Morgan Keller']},
{'coordinate': [34.0977, -117.7118], 'collegeName': 'Pomona College', 'students': ['Ahana Ganguly', 'Xander Koo', 'Sarah Sundermeyer', 'Emma van der Veen']},
{'coordinate': [40.34829155, -74.66508], 'collegeName': 'Princeton University', 'students': ['Linus Wang ']},
{'coordinate': [44.2254211, -76.494605], 'collegeName': "Queen's University", 'students': ['Brinson Elliott']},
{'coordinate': [45.48179645, -122.6314438], 'collegeName': 'Reed College', 'students': ['Claudio Malagrino', 'Celia Morell-Borgstrom']},
{'coordinate': [42.7302, -73.6788], 'collegeName': 'Rensselaer Polytechnic Institute', 'students': ['Helena McDowell']},
{'coordinate': [29.71679145, -95.40478098], 'collegeName': 'Rice University', 'students': ['Emily Hwang']},
{'coordinate': [43.0861, -77.6705], 'collegeName': 'Rochester Institute of Technology', 'students': ['Joshua Donelly-Higgins', 'Kaitlyn  Nakamura', 'Benjamin Beaudry']},
{'coordinate': [59.3498, 18.0707], 'collegeName': 'Royal Institute of Technology (Sweden)', 'students': ['Victor Carlsson']},
{'coordinate': [32.7748159, -117.0738504], 'collegeName': 'San Diego State University', 'students': ['Cory Burton']},
{'coordinate': [37.7219, -122.4782], 'collegeName': 'San Francisco State University', 'students': ['Michael Champagne', 'Sydney Bader', 'Cassie Fong', 'Jasmin Lobo-Johnston']},
{'coordinate': [37.334893, -121.879538], 'collegeName': 'San Jose State University', 'students': ['Helen Herrera Montano', 'Alain Sandraz', 'Lauola Amanoni']},
{'coordinate': [34.4059, -119.6973], 'collegeName': 'Santa Barbara City College', 'students': ['Dorian  Johnson']},
{'coordinate': [37.35153325, -121.9358629], 'collegeName': 'Santa Clara University', 'students': ['Titilola Bolarinwa']},
{'coordinate': [34.1035317, -117.70933], 'collegeName': 'Scripps College', 'students': ['Madeline McCluskey']},
{'coordinate': [40.74337195, -74.24685789], 'collegeName': 'Seton Hall University', 'students': ['Kogulan Paulmurugan']},
{'coordinate': [42.3181, -72.6372], 'collegeName': 'Smith College', 'students': ['Kaitlin Chiu']},
{'coordinate': [38.3404227, -122.6743939], 'collegeName': 'Sonoma State University', 'students': ['Miriam Gollub']},
{'coordinate': [32.84180115, -96.781528], 'collegeName': 'Southern Methodist University', 'students': ['Corinne Smallwood']},
{'coordinate': [37.431089, -122.1693008], 'collegeName': 'Stanford University', 'students': ['Eli Hiss', 'Jerry Hong', 'Alex Liang', 'Avanika Narayan', 'Lauren Nolen', 'Tyler Packard', 'Andrew Tam', 'Dhara Yu', 'Grace Zhao', 'Jonathan Zwiebel']},
{'coordinate': [39.9068, -75.3556], 'collegeName': 'Swarthmore College', 'students': ['Isaac Satz']},
{'coordinate': [43.0392, -76.1351], 'collegeName': 'Syracuse University', 'students': ['Jackson Dahl']},
{'coordinate': [32.7095538, -97.3630816], 'collegeName': 'Texas Christian University', 'students': ['Ben Cleasby']},
{'coordinate': [40.7355, -73.9971], 'collegeName': 'The New School', 'students': ['Yi Ge']},
{'coordinate': [53.3438, -6.2546], 'collegeName': 'Trinity College Dublin', 'students': ['Liam Sherlock']},
{'coordinate': [29.4616939, -98.48347981], 'collegeName': 'Trinity University', 'students': ['Neil Verwillow ']},
{'coordinate': [42.40629165, -71.1197504], 'collegeName': 'Tufts University', 'students': ['Elizabeth Gleeson', 'Justin Yip', 'Johnny Rohrbach']},
{'coordinate': [29.9412208, -90.12029281], 'collegeName': 'Tulane University', 'students': ['Evan Nagesh', 'Gillian Robins']},
{'coordinate': [37.8719, -122.2585], 'collegeName': 'UC Berkeley', 'students': ['Bianca Al-Shamari', 'Alan Huang', 'Neelay Junnarkar', 'Yasmine Kamgarhaghighi', 'Mina Kim', 'Adrienne Kwok', 'Tara Madhav', 'Ethan Teo', 'Ailyn Tong', 'Samarth Venkatasubramaniam', 'Candace Wang', 'Georgia Wood', 'Ethan Ho', 'Ryan Mitra', 'Alice Zhao']},
{'coordinate': [38.5336349, -121.7907725], 'collegeName': 'UC Davis', 'students': ['Lauren Jozefov ', 'Carter Faust', 'Reilly Filter', 'Hayden Libbey', 'Jacqueline Moore', 'Alice On', 'Sean Romeo', 'Yuan Wu', 'Dylan Williams', 'Elena  Willow']},
{'coordinate': [33.6431901, -117.8401648], 'collegeName': 'UC Irvine', 'students': ['Cayla Flagg', 'Chinmay Tyagi']},
{'coordinate': [34.0689, -118.4452], 'collegeName': 'UC Los Angeles', 'students': ['Nicholas Camarena', 'Kimmi Chin', 'Soo Kim', 'Nihar Mitra', 'Tai Nguyen', "Andrea O'Riordan", 'Charles Stoksik', 'Flora Yu']},
{'coordinate': [37.3631, -120.4301], 'collegeName': 'UC Merced', 'students': ['Joao De Pina']},
{'coordinate': [33.9737, -117.3281], 'collegeName': 'UC Riverside', 'students': ['Daniel Baeza', 'Jonathan Rastegar', 'Katelyn Vi', 'Rebecca  Lettes ']},
{'coordinate': [32.8801, -117.234], 'collegeName': 'UC San Diego', 'students': ['Isabella Bernard', 'Anthony Chen', 'Irene Choi', 'Daniel Li', 'Natalie Maloney', 'Alexandra  Westgaard']},
{'coordinate': [34.4163, -119.8485189], 'collegeName': 'UC Santa Barbara', 'students': ['Josh Brigel', 'Mason Corey', 'Madeleine Frick', 'Kathleen  Gaffney', 'Michelle Leong', 'Rima Parekh', 'Yashvi Tibrewal', 'Kai Oda', 'Alexandra  Stump', 'Dalia van Zyll']},
{'coordinate': [37.00079505, -122.0629317], 'collegeName': 'UC Santa Cruz', 'students': ['Malin Minborg', 'James Ngo', 'Gabriel Sanchez', 'Siddarth Sharma']},
//{'coordinate': [0.0, 0.0], 'collegeName': 'Undisclosed', 'students': ['Teleri Abrahamson-Smith', 'Ajibola Akinola', 'Katie Rose Ayala', 'Chandler Bastiansen', 'Jose Becerra', 'Benjamin Beisheim', 'Charlotte Brinkley', 'Brandon Brown', 'Christopher Buenrostro', 'Emily Calnan', 'David Chernyak', 'Molly Coker', 'James Cullen', 'Katherine DeAndre', 'Jianxing Deng', 'Aron Ecoff', 'Maddie  Feldmeier', 'James Forman', 'Jamal Gage', 'Lesli Garay Lizarraga', 'Miguel Garcia', 'Melissa Guillen', 'Katherine Hetterly', 'Rebecca Hidalgo', 'Albert Hwang', 'Abigail Jalpa', 'Griffin Jarrell-Desch', 'Sotiris Koutsoyannis', 'Paul Labib', 'Jason Leung', 'Aramis Lopez', 'Xinger Luo', 'Maxwell Makoski', 'Victor Manuel Manalac', 'Noah Marriott', 'Christopher Martinez', 'Brett McBride', 'Britney McGraw', 'Mary McNamara', 'Anna Medoff', 'Gabriel Minjarez', 'Blake Moffitt', 'Rebecca Mogensen', 'Andrea Molina', 'Jonathan Montes', 'Katherine Montgomery', 'Brianna Munoz', 'Zahra Muzaffar', 'Eric Neuman', 'Serina Nguyen', "Catherine O'Connor", 'Daniel Ochoa-Rodriguez', 'Sophie Pedersen', 'Brendon Pena', 'Stephanie Perez', 'Jonathan Prabhu', 'Kathrin Pramstaller', 'Josue Pulido', 'thomas rauner-swan', 'Jeremy Rosenbaum', 'Nicholas Russell', 'Iban Sadowski', 'Amanda Santa Gadea', 'Tomer Sherman', 'Mayerly Short', 'Brendan Sperling', 'Angus Stayte', 'Matthew Stevens', 'Yuhao Su', 'Isabel Taggart', 'Alexander Tarng', 'Miles Tention', 'Flynn Thompson', 'Elenoa Tulua', 'Maryland Valdez-Gonzalez', 'Edith Vences', 'Alexander Wang', 'Michael Wang', 'Ty Wilcox', 'Celia Willner', 'Tiaira Witherspoon', 'Matthew Woon', 'Trevor Woon', 'Brandon Wu', 'Spencer Wycoff', 'Fan Xu', 'Joseph Yang', 'Luca Zaharias']},
{'coordinate': [42.817, -73.9298], 'collegeName': 'Union College', 'students': ['Leo Minami']},
{'coordinate': [33.21050415, -87.54902734], 'collegeName': 'University of Alabama', 'students': ['Haley Chalmers', 'Maya Heron']},
{'coordinate': [33.45205165, -112.0636788], 'collegeName': 'University of Arizona', 'students': ['Tanner Newell', 'Hana Kamarei']},
{'coordinate': [41.7846322, -87.6007443], 'collegeName': 'University of Chicago', 'students': ['Zoe Dellaert', 'Jacques  Manjarrez', 'Laura Sieh']},
{'coordinate': [40.00938065, -105.2660799], 'collegeName': 'University of Colorado Boulder', 'students': ['Carson  Cordova', 'Scott Garland', 'Maya Katz', 'Eric Kim', 'Jesse Leonard', 'Blake Novak', 'Erin Reynolds']},
{'coordinate': [41.8077, -72.254], 'collegeName': 'University of Connecticut', 'students': ['Danielle Macuil']},
{'coordinate': [55.9445, -3.1892], 'collegeName': 'University of Edinburgh', 'students': ['Lydia Brownell']},
{'coordinate': [21.2969, -157.8171], 'collegeName': 'University of Hawaii', 'students': ['Troy Henderson ']},
{'coordinate': [40.1006938, -88.23134951], 'collegeName': 'University of Illinois at Urbana-Champaign', 'students': ['Kevin Chen', 'Raphael  Long']},
{'coordinate': [41.6627, -91.5549], 'collegeName': 'University of Iowa', 'students': ['Bennet Huang']},
{'coordinate': [34.10003375, -117.7725888], 'collegeName': 'University of La Verne', 'students': ['Ryan  Mendoza ']},
{'coordinate': [44.9012, -68.6667], 'collegeName': 'University of Maine', 'students': ['Natasha Minskoff']},
{'coordinate': [38.9869, -76.9426], 'collegeName': 'University of Maryland, College Park', 'students': ['Sean Chapman', 'Derek Schoenberger']},
{'coordinate': [42.2942077, -83.71001484], 'collegeName': 'University of Michigan', 'students': ['Daniella Maydan', 'Noa Ben-Efraim', 'Thomas Crouch', 'Rory Nyffenegger', 'Dillon Scheel', 'Avi Tachna-Fram', 'Ian Woodfill']},
{'coordinate': [35.91256775, -79.05488911], 'collegeName': 'University of North Carolina, Chapel Hill', 'students': ['Mason Wittman', 'Jordan Wooten']},
{'coordinate': [44.0453484, -123.0757923], 'collegeName': 'University of Oregon', 'students': ['Thorin  Haussecker', 'Matilda Kenrick', 'Louie Marzano']},
{'coordinate': [39.9522, -75.1932], 'collegeName': 'University of Pennsylvania', 'students': ['Jackson Wood', 'Nancy Yang', 'Sean Young']},
{'coordinate': [34.0625269, -117.1640951], 'collegeName': 'University of Redlands', 'students': ['Elise Kiya']},
{'coordinate': [32.7726805, -117.1889765], 'collegeName': 'University of San Diego', 'students': ['Fiona Green', 'Rutger Van Hulsen ', 'Quinn Knoblock']},
{'coordinate': [47.6092, -122.3177], 'collegeName': 'University of Seattle', 'students': ['Theodosia Stewart']},
{'coordinate': [34.0219686, -118.2858693], 'collegeName': 'University of Southern California', 'students': ['Julie Chandler', 'Ethan Kao', 'Yahli Malchin', 'Talia Malchin', 'David Willner', 'Trisha  Wittenbrink ']},
{'coordinate': [30.2849, -97.7341], 'collegeName': 'University of Texas at Austin', 'students': ['Jerry Huang', 'Gregory Jerian', 'Flavia Stiglich']},
{'coordinate': [40.7649, -111.8421], 'collegeName': 'University of Utah', 'students': ['Eric Maser', 'Eve Merritt', 'Jonathan  Young ']},
{'coordinate': [47.65288725, -122.3111144], 'collegeName': 'University of Washington', 'students': ['Caitlin Drover', 'Jack Fitton', 'Connor Hu', 'Kirsten Kwan', 'Cezanne Lane', 'Robbie  Nixon', 'Tess Preising', 'Matthew Seto', 'Sam Yun', 'Maria Akrivouli', 'Leah Benque', 'Nathaniel Hancock', 'Jack Simison']},
{'coordinate': [43.07988825, -89.43074566], 'collegeName': 'University of Wisconsin', 'students': ['Jordan Schilling']},
{'coordinate': [36.14422155, -86.80274109], 'collegeName': 'Vanderbilt University', 'students': ['Sarah Shapiro', 'Annalise Wang', 'Jessica  Wong']},
{'coordinate': [37.2284, -80.4234], 'collegeName': 'Virginia Tech', 'students': ['Marcel Colchen']},
{'coordinate': [46.7319, -117.1542], 'collegeName': 'Washington State University', 'students': ['Kieran Godfrey']},
{'coordinate': [38.6482764, -90.30793085], 'collegeName': 'Washington University in St. Louis', 'students': ['Stefan Quach', 'Kevin Zhang', 'John Liu']},
{'coordinate': [42.2936, -71.3059], 'collegeName': 'Wellesley College', 'students': ['Nicole Li', 'Anmol Nagar', 'Isabel Nichoson', 'Jessica Wu']},
{'coordinate': [48.7335, -122.4873], 'collegeName': 'Western Washington University', 'students': ['Chloe Patterson']},
{'coordinate': [40.7315, -111.8552], 'collegeName': 'Westminster College', 'students': ['Mara Zenger']},
{'coordinate': [46.0706, -118.3306], 'collegeName': 'Whitman College', 'students': ['Thibault Collignon', 'Sherwin Amsbaugh ']},
{'coordinate': [44.9345509, -123.0334156], 'collegeName': 'Willamette University', 'students': ['Matthew Aiu', 'Nora Danie']},
//{'coordinate': [0.0, 0.0], 'collegeName': '', 'students': ['David Anwyl', 'Henry Badger', 'Josh Code', 'Eelis Copeland', 'Donnesh Farmanfarmaian', 'Mackenzie Ferrell', 'Fe Hmelar', 'Katie Hoffman ', 'Leanne Miron', 'Leila Sidow', 'Layla Solatan', 'Moa Stakeberg', 'Elin Stakeberg', 'Georgia Touloukian ', 'Ryan Tri', 'Shahram Tayyebi', 'Nathan Zeidwerg', 'Brian Kang', 'Emilia Diaz-Magaloni ', 'Blaine Williams', 'Stella Carpenter', 'Helena Mcfadden ']},
{'coordinate': [51.5144, -0.1174], 'collegeName': 'London School of Economics and Political Science ', 'students': ['Tucker Dolmatch']},
{'coordinate': [50.6697, 4.6156], 'collegeName': 'Université catholique de Louvain', 'students': ['Laure Papleux']},
{'coordinate': [42.8125, -1.6458], 'collegeName': 'Universidad de Navarra', 'students': ['Paloma Ruiz']},
{'coordinate': [25.3183, 51.4456], 'collegeName': 'Northwestern University in Qatar', 'students': ['David Wu']},
];